/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/': RouteRecordInfo<
      '/albums/',
      '/albums',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/daily/': RouteRecordInfo<
      '/albums/daily/',
      '/albums/daily',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/albums/work/': RouteRecordInfo<
      '/albums/work/',
      '/albums/work',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/实习小记': RouteRecordInfo<
      '/posts/实习小记',
      '/posts/%E5%AE%9E%E4%B9%A0%E5%B0%8F%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/是啊，我也曾彻夜难眠': RouteRecordInfo<
      '/posts/是啊，我也曾彻夜难眠',
      '/posts/%E6%98%AF%E5%95%8A%EF%BC%8C%E6%88%91%E4%B9%9F%E6%9B%BE%E5%BD%BB%E5%A4%9C%E9%9A%BE%E7%9C%A0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sponsors/': RouteRecordInfo<
      '/sponsors/',
      '/sponsors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/world/': RouteRecordInfo<
      '/world/',
      '/world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.39_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parser@7.29.7_@nuxt+kit@3.21.8_magicast@0.5.3__@types+markdown-it_00fdef99004d51e622ddb1415e1652f0/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/index.md': {
      routes:
        | '/albums/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/daily/index.md': {
      routes:
        | '/albums/daily/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/albums/work/index.md': {
      routes:
        | '/albums/work/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.39_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_magicast@0.5.3_vue@3.5.39_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/实习小记.md': {
      routes:
        | '/posts/实习小记'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/是啊，我也曾彻夜难眠.md': {
      routes:
        | '/posts/是啊，我也曾彻夜难眠'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/sponsors/index.md': {
      routes:
        | '/sponsors/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/world/index.md': {
      routes:
        | '/world/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
